import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import type { AifImplementedProfileType, AifSettings } from "../core/aifTypes";
import { implementedAifProfiles } from "../profiles/aifProfileRegistry";
import { AIF_SETTINGS_PRESETS, defaultAifSettings, migrateAifSettings } from "../state/aifStore";
import { readAifStorage, writeAifSettingsStorage } from "../state/aifStorage";

type Props = { settings: AifSettings; onChange: (next: AifSettings) => void; onClose: () => void };
type SettingKey = keyof AifSettings;

export function AifIndicatorSettings({ settings, onChange, onClose }: Props) {
  const [search, setSearch] = useState("");
  const [transfer, setTransfer] = useState("");
  const defaults = useMemo(defaultAifSettings, []);
  const profiles = implementedAifProfiles();
  const patch = (value: Partial<AifSettings>) => onChange(migrateAifSettings({ ...settings, ...value }));
  const reset = (keys: SettingKey[]) => patch(Object.fromEntries(keys.map((key) => [key, defaults[key]])) as Partial<AifSettings>);
  const visible = (title: string) => !search || title.toLowerCase().includes(search.toLowerCase());
  const horizonPresets = [2000, 5000, 10000, 20000, 50000, 100000];
  const horizonPreset = horizonPresets.includes(settings.lookbackBars) ? String(settings.lookbackBars) : "custom";
  const applyImport = () => { try { onChange(migrateAifSettings(JSON.parse(transfer))); } catch { /* Preserve current settings on invalid JSON. */ } };
  const saveCustom = () => writeAifSettingsStorage("bt_aif_custom_preset", JSON.stringify(settings));
  const loadCustom = () => { const value = readAifStorage("bt_aif_custom_preset"); if (value) { try { onChange(migrateAifSettings(JSON.parse(value))); } catch { /* Ignore invalid old preset. */ } } };
  return <div className="indicator-settings profile-settings aif-settings" data-testid="aif-settings">
    <div className="indicator-settings-title"><span>A.I.F. CONTROL SYSTEM</span><button type="button" onClick={onClose}>DONE</button></div>
    <div className="aif-settings-toolbar"><input aria-label="Search A.I.F. settings" placeholder="Search settings" value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="A.I.F. preset" defaultValue=""><option value="" disabled>Load preset</option>{Object.keys(AIF_SETTINGS_PRESETS).map((name) => <option key={name}>{name}</option>)}</select><button type="button" onClick={(event) => { const select = event.currentTarget.previousElementSibling as HTMLSelectElement; if (select.value) patch(AIF_SETTINGS_PRESETS[select.value]); }}>APPLY</button><button type="button" onClick={saveCustom}>SAVE</button><button type="button" onClick={loadCustom}>CUSTOM</button><button type="button" onClick={() => onChange(defaults)}>RESET ALL</button></div>
    {visible("Profile") && <Group title="PROFILE" onReset={() => reset(["primaryProfile", "profilePlacement", "profileWidth", "profileHorizontalOffset", "profileNormalization", "opacity"])} open>
      <Select label="Primary Profile" value={settings.primaryProfile} onChange={(value) => patch({ primaryProfile: value as AifImplementedProfileType })} options={profiles.map((profile) => [profile.id, profile.name])} />
      <ProfileModeControls settings={settings} patch={patch} />
      <Select label="Placement" value={settings.profilePlacement} onChange={(value) => patch({ profilePlacement: value as AifSettings["profilePlacement"] })} options={[["right","Right"],["left","Left"],["both","Both"],["overlay","Overlay"]]} />
      <NumberField label="Width" value={settings.profileWidth} min={5} max={60} onChange={(profileWidth) => patch({ profileWidth })} />
      <NumberField label="Horizontal Offset" value={settings.profileHorizontalOffset} min={0} max={400} onChange={(profileHorizontalOffset) => patch({ profileHorizontalOffset })} />
      <Select label="Normalization" value={settings.profileNormalization} onChange={(value) => patch({ profileNormalization: value as AifSettings["profileNormalization"] })} options={[["raw","Raw"],["percent-max","Percent Maximum"],["percentile","Percentile"],["z-score","Z-Score"],["robust-z-score","Robust Z-Score"],["log","Log"]]} />
      <RangeField label="Profile Opacity" value={settings.opacity} onChange={(opacity) => patch({ opacity })} />
    </Group>}
    {visible("Range") && <Group title="RANGE" onReset={() => reset(["rangeMode", "lookbackBars", "anchorTime"])} open>
      <Select label="Range Mode" value={settings.rangeMode} onChange={() => {}} options={[["lookback","Rolling Lookback"]]} disabled />
      <Select label="History Horizon" value={horizonPreset} onChange={(value) => value !== "custom" && patch({ lookbackBars: Number(value) })} options={[...horizonPresets.map((value) => [String(value), `${value.toLocaleString()} bars`]), ["custom","Custom"]]} />
      {horizonPreset === "custom" && <NumberField label="Custom Bars" value={settings.lookbackBars} min={100} max={100000} step={100} onChange={(lookbackBars) => patch({ lookbackBars })} />}
      <span className="aif-settings-note">VISIBLE / ANCHORED RANGE REQUIRES A WORKER CAMERA-RANGE CONTRACT</span>
    </Group>}
    {visible("Resolution") && <Group title="RESOLUTION" onReset={() => reset(["bucketMode", "rowCount", "fixedPriceSize", "percentageBucket", "sourceResolution"])}>
      <Select label="Bucket Mode" value={settings.bucketMode} onChange={(value) => patch({ bucketMode: value as AifSettings["bucketMode"], logarithmic: value === "logarithmic" })} options={[["fixed-rows","Fixed Rows"],["fixed-price","Fixed Price"],["tick","Tick Size"],["percentage","Percentage"],["logarithmic","Logarithmic"],["atr-normalized","ATR-Normalized"],["adaptive","Adaptive"]]} />
      <NumberField label="Rows" value={settings.rowCount} min={50} max={2000} onChange={(rowCount) => patch({ rowCount })} />
      {(settings.bucketMode === "fixed-price" || settings.bucketMode === "tick") && <NumberField label="Price / Tick Size" value={settings.fixedPriceSize} min={0.00000001} max={1e9} step={0.0001} onChange={(fixedPriceSize) => patch({ fixedPriceSize })} />}
      {settings.bucketMode === "percentage" && <NumberField label="Bucket Percent" value={settings.percentageBucket} min={0.0001} max={25} step={0.01} onChange={(percentageBucket) => patch({ percentageBucket })} />}
      <Select label="Source Resolution" value={settings.sourceResolution} onChange={() => {}} options={[["best","Best Available From Adapter"]]} disabled />
      {settings.rowCount > 500 && <span className="aif-settings-warning">VERIFY ADAPTER RESOLUTION BEFORE INTERPRETING FINE PROFILE ROWS</span>}
    </Group>}
    {visible("Value Area") && <Group title="VALUE AREA" onReset={() => reset(["showValueArea", "valueAreaPercent", "showPoc", "pocMode", "showVah", "showVal", "valueAreaColor", "valueAreaOpacity"])} open>
      <Toggle label="Show Value Area" checked={settings.showValueArea} onChange={(showValueArea) => patch({ showValueArea })} />
      <NumberField label="Value Area Percent" value={settings.valueAreaPercent} min={1} max={99} onChange={(valueAreaPercent) => patch({ valueAreaPercent })} />
      <Toggle label="Show POC" checked={settings.showPoc} onChange={(showPoc) => patch({ showPoc })} />
      <Select label="POC Mode" value={settings.pocMode} onChange={() => {}} options={[["fixed","Fixed Completed Profile"]]} disabled />
      <span className="aif-settings-note">DEVELOPING POC SERIES IS NOT PUBLISHED BY THE CURRENT WORKER MODEL</span>
      <Toggle label="Show VAH" checked={settings.showVah} onChange={(showVah) => patch({ showVah })} /><Toggle label="Show VAL" checked={settings.showVal} onChange={(showVal) => patch({ showVal })} />
      <ColorField label="Value Area Color" value={settings.valueAreaColor} onChange={(valueAreaColor) => patch({ valueAreaColor })} />
      <RangeField label="Value Area Opacity" value={settings.valueAreaOpacity} onChange={(valueAreaOpacity) => patch({ valueAreaOpacity })} />
    </Group>}
    {visible("Node Detection") && <Group title="NODE DETECTION" onReset={() => reset(["nodeMethod", "lvnPercentileThreshold", "lvnNeighborWindow", "lvnMinimumContiguousRows", "lvnInternalGapRows", "lvnMinimumWidthRows", "lvnMaximumWidthRows", "lvnMergeDistanceRows", "lvnMinimumContrast", "lvnMinimumStrength", "lvnEdgeExclusionRows"])}>
      <Select label="Method" value={settings.nodeMethod} onChange={(value) => patch({ nodeMethod: value as AifSettings["nodeMethod"] })} options={[["hybrid-structural","Hybrid Structural"],["percentile","Percentile"],["neighbor-contrast","Neighbor Contrast"],["robust-z-score","Robust Z-Score"],["valley-detection","Valley Detection"],["relative-poc","Relative to POC"]]} />
      <RangeField label="LVN Percentile" value={settings.lvnPercentileThreshold} onChange={(lvnPercentileThreshold) => patch({ lvnPercentileThreshold })} />
      <NumberField label="Neighbor Window" value={settings.lvnNeighborWindow} min={1} max={30} onChange={(lvnNeighborWindow) => patch({ lvnNeighborWindow })} />
      <NumberField label="Minimum Contiguous Rows" value={settings.lvnMinimumContiguousRows} min={1} max={20} onChange={(lvnMinimumContiguousRows) => patch({ lvnMinimumContiguousRows })} />
      <NumberField label="Internal Gap Tolerance" value={settings.lvnInternalGapRows} min={0} max={5} onChange={(lvnInternalGapRows) => patch({ lvnInternalGapRows })} />
      <NumberField label="Minimum / Maximum Width" value={settings.lvnMinimumWidthRows} min={1} max={settings.lvnMaximumWidthRows} onChange={(lvnMinimumWidthRows) => patch({ lvnMinimumWidthRows })} />
      <NumberField label="Maximum Width Rows" value={settings.lvnMaximumWidthRows} min={settings.lvnMinimumWidthRows} max={100} onChange={(lvnMaximumWidthRows) => patch({ lvnMaximumWidthRows })} />
      <NumberField label="Merge Distance Rows" value={settings.lvnMergeDistanceRows} min={0} max={20} onChange={(lvnMergeDistanceRows) => patch({ lvnMergeDistanceRows })} />
      <NumberField label="Minimum Contrast" value={settings.lvnMinimumContrast} min={1} max={10} step={0.05} onChange={(lvnMinimumContrast) => patch({ lvnMinimumContrast })} />
      <RangeField label="Minimum Strength" value={settings.lvnMinimumStrength} onChange={(lvnMinimumStrength) => patch({ lvnMinimumStrength })} />
      <NumberField label="Edge Exclusion Rows" value={settings.lvnEdgeExclusionRows} min={0} max={50} onChange={(lvnEdgeExclusionRows) => patch({ lvnEdgeExclusionRows })} />
      <Toggle label="Show HVNs" checked={settings.showHvns} onChange={(showHvns) => patch({ showHvns })} /><Toggle label="Show LVNs" checked={settings.showLvns} onChange={(showLvns) => patch({ showLvns })} /><Toggle label="Show Minor Nodes" checked={settings.showMinorNodes} onChange={(showMinorNodes) => patch({ showMinorNodes })} />
    </Group>}
    {visible("Future LVNs") && <Group title="FUTURE LVNs" onReset={() => reset(["showFutureLvns", "futureLvnPolicy", "futureLvnMinimumStability", "futureLvnMinimumContrast", "futureLvnMinimumConfidence", "futureLvnMaxAbove", "futureLvnMaxBelow", "futureLvnMaxTotal", "futureLvnMinimumScore", "futureLvnZoneOpacity", "futureLvnBoundaryOpacity", "futureLvnShowCenter", "futureLvnShowMinimumActivity", "futureLvnShowScore", "futureLvnShowLookback", "futureLvnShowState", "futureLvnKeepTested", "futureLvnKeepInvalidated"])} open>
      <Toggle label="Show Future LVNs" checked={settings.showFutureLvns} onChange={(showFutureLvns) => patch({ showFutureLvns })} />
      <Select label="Projection Policy" value={settings.futureLvnPolicy} onChange={(value) => patch({ futureLvnPolicy: value as AifSettings["futureLvnPolicy"] })} options={[["major-untested","Major Untested"],["untested-first-test","Untested + First Test"],["all-qualified","All Qualified"],["active-lifecycle","Active Lifecycle"]]} />
      <RangeField label="Minimum Stability" value={settings.futureLvnMinimumStability} onChange={(futureLvnMinimumStability) => patch({ futureLvnMinimumStability })} /><RangeField label="Minimum Confidence" value={settings.futureLvnMinimumConfidence} onChange={(futureLvnMinimumConfidence) => patch({ futureLvnMinimumConfidence })} />
      <NumberField label="Minimum Contrast" value={settings.futureLvnMinimumContrast} min={1} max={10} step={0.05} onChange={(futureLvnMinimumContrast) => patch({ futureLvnMinimumContrast })} /><RangeField label="Minimum Display Score" value={settings.futureLvnMinimumScore} onChange={(futureLvnMinimumScore) => patch({ futureLvnMinimumScore })} />
      <NumberField label="Max Above Price" value={settings.futureLvnMaxAbove} min={0} max={20} onChange={(futureLvnMaxAbove) => patch({ futureLvnMaxAbove })} /><NumberField label="Max Below Price" value={settings.futureLvnMaxBelow} min={0} max={20} onChange={(futureLvnMaxBelow) => patch({ futureLvnMaxBelow })} /><NumberField label="Max Total" value={settings.futureLvnMaxTotal} min={1} max={30} onChange={(futureLvnMaxTotal) => patch({ futureLvnMaxTotal })} />
      <RangeField label="Zone Fill Opacity" value={settings.futureLvnZoneOpacity} onChange={(futureLvnZoneOpacity) => patch({ futureLvnZoneOpacity })} /><RangeField label="Boundary Opacity" value={settings.futureLvnBoundaryOpacity} onChange={(futureLvnBoundaryOpacity) => patch({ futureLvnBoundaryOpacity })} />
      <Toggle label="Show Center" checked={settings.futureLvnShowCenter} onChange={(futureLvnShowCenter) => patch({ futureLvnShowCenter })} /><Toggle label="Show Minimum Activity" checked={settings.futureLvnShowMinimumActivity} onChange={(futureLvnShowMinimumActivity) => patch({ futureLvnShowMinimumActivity })} /><Toggle label="Show Score" checked={settings.futureLvnShowScore} onChange={(futureLvnShowScore) => patch({ futureLvnShowScore })} /><Toggle label="Show Lookback" checked={settings.futureLvnShowLookback} onChange={(futureLvnShowLookback) => patch({ futureLvnShowLookback })} /><Toggle label="Show State" checked={settings.futureLvnShowState} onChange={(futureLvnShowState) => patch({ futureLvnShowState })} />
      <Select label="Keep Invalidated" value={settings.futureLvnKeepInvalidated} onChange={(value) => patch({ futureLvnKeepInvalidated: value as AifSettings["futureLvnKeepInvalidated"] })} options={[["off","Off"],["faded","Faded"],["timeline-only","Timeline Only"]]} />
      <Toggle label="Keep Tested Zones" checked={settings.futureLvnKeepTested} onChange={(futureLvnKeepTested) => patch({ futureLvnKeepTested })} />
    </Group>}
    {visible("Support Resistance") && <Group title="SUPPORT / RESISTANCE" onReset={() => reset(["showSupportResistance", "extendLevels", "zoneIntensity"])}><Toggle label="Show Structural S/R" checked={settings.showSupportResistance} onChange={(showSupportResistance) => patch({ showSupportResistance })} /><Toggle label="Extend Zones" checked={settings.extendLevels} onChange={(extendLevels) => patch({ extendLevels })} /><RangeField label="Zone Intensity" value={settings.zoneIntensity} onChange={(zoneIntensity) => patch({ zoneIntensity })} /></Group>}
    {visible("Secondary Profile") && <Group title="SECONDARY PROFILE" onReset={() => reset(["secondaryProfile", "comparisonMode"])}><Select label="Secondary Profile" value={settings.secondaryProfile} onChange={(value) => patch({ secondaryProfile: value as AifSettings["secondaryProfile"] })} options={[["off","Off"], ...profiles.filter((profile) => profile.id !== settings.primaryProfile).map((profile) => [profile.id, profile.name])]} /><Select label="Comparison Domain" value={settings.comparisonMode} onChange={(value) => patch({ comparisonMode: value as AifSettings["comparisonMode"] })} options={[["shared-domain","Shared Domain"],["independent","Independent"]]} /></Group>}
    {visible("CHoB") && <Group title="CHoB" onReset={() => reset(["minimumConfidence", "enableImmConfirmation"])}><RangeField label="Minimum Confidence" value={settings.minimumConfidence} onChange={(minimumConfidence) => patch({ minimumConfidence })} /><Toggle label="IMM Confirmation" checked={settings.enableImmConfirmation} onChange={(enableImmConfirmation) => patch({ enableImmConfirmation })} /></Group>}
    {visible("IMM") && <Group title="IMM" onReset={() => reset(["minimumWallPersistence", "showLiquidityConfluence"])}><span className="aif-settings-warning">IMM DEPTH MEMORY IS UNAVAILABLE IN THE CURRENT A.I.F. PAYLOAD</span><NumberField label="Minimum Wall Persistence" value={settings.minimumWallPersistence} min={1} max={3600} onChange={(minimumWallPersistence) => patch({ minimumWallPersistence })} disabled /><Toggle label="Wall Confluence" checked={settings.showLiquidityConfluence} onChange={(showLiquidityConfluence) => patch({ showLiquidityConfluence })} disabled /></Group>}
    {visible("Timeline") && <Group title="TIMELINE" onReset={() => reset(["showTimeline", "timelineHeight", "timelineHorizon", "maximumTimelineEvents"])}><Toggle label="Show Timeline" checked={settings.showTimeline} onChange={(showTimeline) => patch({ showTimeline })} /><NumberField label="Timeline Height" value={settings.timelineHeight} min={32} max={120} onChange={(timelineHeight) => patch({ timelineHeight })} /><NumberField label="Timeline Horizon" value={settings.timelineHorizon} min={20} max={5000} onChange={(timelineHorizon) => patch({ timelineHorizon })} /><NumberField label="Maximum Events" value={settings.maximumTimelineEvents} min={20} max={500} onChange={(maximumTimelineEvents) => patch({ maximumTimelineEvents })} /></Group>}
    {visible("Visuals") && <Group title="VISUALS" onReset={() => reset(["labelDensity", "showLabels", "showStatisticsCard", "showDataQuality"])}><Select label="Label Density" value={settings.labelDensity} onChange={(value) => patch({ labelDensity: value as AifSettings["labelDensity"] })} options={[["low","Low"],["medium","Medium"],["high","High"]]} /><Toggle label="Show Labels" checked={settings.showLabels} onChange={(showLabels) => patch({ showLabels })} /><Toggle label="Statistics Card" checked={settings.showStatisticsCard} onChange={(showStatisticsCard) => patch({ showStatisticsCard })} /><Toggle label="Data Quality" checked={settings.showDataQuality} onChange={(showDataQuality) => patch({ showDataQuality })} /></Group>}
    {visible("Performance") && <Group title="PERFORMANCE" onReset={() => reset(["calculationMode", "maximumVisibleNodes", "multiLookbackStability", "resolutionStability"])}><Select label="Calculation Mode" value={settings.calculationMode} onChange={(value) => patch({ calculationMode: value as AifSettings["calculationMode"] })} options={[["performance","Performance"],["balanced","Balanced"],["maximum-detail","Maximum Detail"]]} /><NumberField label="Maximum Visible Nodes" value={settings.maximumVisibleNodes} min={4} max={80} onChange={(maximumVisibleNodes) => patch({ maximumVisibleNodes })} /><Select label="Multi-Lookback Stability" value={settings.multiLookbackStability} onChange={(value) => patch({ multiLookbackStability: value as AifSettings["multiLookbackStability"] })} options={[["off","Off"],["major","Major Nodes Only"],["all","All Nodes"]]} /><Select label="Resolution Stability" value={settings.resolutionStability} onChange={() => {}} options={[["off","Unavailable With Current Adapter Payload"]]} disabled /></Group>}
    {visible("Data Quality") && <Group title="DATA QUALITY" onReset={() => reset(["showDataQuality"])}><div className="aif-settings-readout"><span>Source <b>{settings.sourceResolution}</b></span><span>Requested <b>{settings.lookbackBars.toLocaleString()} bars</b></span><span>Algorithm <b>hybrid-structural-v1</b></span><span>Quality <b>Estimated until classified flow is available</b></span></div></Group>}
    {visible("Import Export") && <Group title="IMPORT / EXPORT" onReset={() => setTransfer("")}><textarea aria-label="A.I.F. settings JSON" value={transfer} onChange={(event) => setTransfer(event.target.value)} placeholder="Settings JSON" /><div className="aif-settings-actions"><button type="button" onClick={() => { const value = JSON.stringify(settings, null, 2); setTransfer(value); void navigator.clipboard?.writeText(value); }}>COPY EXPORT</button><button type="button" onClick={applyImport}>IMPORT</button></div></Group>}
  </div>;
}

function ProfileModeControls({ settings, patch }: { settings: AifSettings; patch: (value: Partial<AifSettings>) => void }) {
  if (settings.primaryProfile === "volatility") return <div className="aif-profile-mode-controls" data-profile-mode="volatility"><b>VOLATILITY PROFILE</b><span>Range expansion and variance distributed by price.</span><Select label="Estimator" value={settings.volatilityEstimator} onChange={(value) => patch({ volatilityEstimator: value as AifSettings["volatilityEstimator"] })} options={[["composite","Composite"],["true-range","True Range"],["log-return-variance","Log Return Variance"],["parkinson","Parkinson"]]} /><Select label="Allocation" value={settings.volatilityAllocation} onChange={(value) => patch({ volatilityAllocation: value as AifSettings["volatilityAllocation"] })} options={[["body-weighted","Body Weighted"],["uniform-range","Uniform Range"],["close-location","Close Location"]]} /></div>;
  if (settings.primaryProfile === "tpo") return <div className="aif-profile-mode-controls" data-profile-mode="tpo"><b>TPO PROFILE</b><span>Estimated time-at-price from source-period range visits.</span><NumberField label="TPO Period Minutes" value={settings.tpoPeriodMinutes} min={1} max={1440} onChange={(tpoPeriodMinutes) => patch({ tpoPeriodMinutes })} /></div>;
  if (settings.primaryProfile === "delta") return <div className="aif-profile-mode-controls" data-profile-mode="delta"><b>DELTA PROFILE</b><span>Estimated signed flow from OHLCV pressure. Classified aggressor flow is not claimed.</span></div>;
  if (settings.primaryProfile === "pressure") return <div className="aif-profile-mode-controls" data-profile-mode="pressure"><b>PRESSURE PROFILE</b><span>Body, close-location and wick pressure composite by price.</span></div>;
  return <div className="aif-profile-mode-controls" data-profile-mode="volume"><b>VOLUME PROFILE</b><span>Conserved candle volume allocated across each traded range.</span></div>;
}

function Group({ title, children, onReset, open = false }: { title: string; children: ReactNode; onReset: () => void; open?: boolean }) { return <details className="aif-settings-group" open={open}><summary><b>{title}</b><button type="button" onClick={(event) => { event.preventDefault(); event.stopPropagation(); onReset(); }}>RESET</button></summary><section className="indicator-settings-section">{children}</section></details>; }
function Select({ label, value, options, onChange, disabled = false }: { label: string; value: string | number; options: Array<Array<string | number>>; onChange: (value: string) => void; disabled?: boolean }) { return <label>{label}<select value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)}>{options.map(([value, name]) => <option key={String(value)} value={value}>{name}</option>)}</select></label>; }
function NumberField({ label, value, min, max, step = 1, onChange, disabled = false }: { label: string; value: number; min: number; max: number; step?: number; onChange: (value: number) => void; disabled?: boolean }) { return <label>{label}<input type="number" value={value} min={min} max={max} step={step} disabled={disabled} onChange={(event) => onChange(Math.max(min, Math.min(max, Number(event.target.value))))} /></label>; }
function RangeField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label>{label}<input type="range" min={0} max={100} value={value} onChange={(event) => onChange(Number(event.target.value))} /><span>{value}</span></label>; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label>{label}<input type="color" value={value} onChange={(event) => onChange(event.target.value)} /><span>{value.toUpperCase()}</span></label>; }
function Toggle({ label, checked, onChange, disabled = false }: { label: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean }) { return <label>{label}<input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /></label>; }
