import { BookOpen, Library, Send } from "lucide-react";
import { useState } from "react";
import { professionalNetworkApi } from "../networkApi";

export function AssetsPanel({ assets, isOwner, onReload }: { assets: { indicators: Array<Record<string, unknown>>; strategies: Array<Record<string, unknown>> }; isOwner: boolean; onReload: () => void }) {
  const [type, setType] = useState<"indicator" | "strategy">("indicator");
  const [draft, setDraft] = useState({ name: "", description: "", version: "1.0.0", market: "Crypto", timeframe: "1H", riskProfile: "balanced", visibility: "public" });
  const [status, setStatus] = useState("");
  const publish = async () => { try { await professionalNetworkApi.publishAsset(type, draft); setDraft({ ...draft, name: "", description: "" }); setStatus("Published professional asset."); onReload(); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } };
  return <div className="pn-assets-layout"><section className="pn-assets-list"><header><Library size={14} /><strong>Published Indicators</strong></header>{assets.indicators.length ? assets.indicators.map((asset) => <AssetCard key={String(asset.id)} asset={asset} type="Indicator" />) : <div className="pn-empty"><Library size={18} /><strong>No Published Indicators</strong><span>Permission-approved indicators can be published without exposing source code.</span></div>}<header><BookOpen size={14} /><strong>Published Strategies</strong></header>{assets.strategies.length ? assets.strategies.map((asset) => <AssetCard key={String(asset.id)} asset={asset} type="Strategy" />) : <div className="pn-empty"><BookOpen size={18} /><strong>No Published Strategies</strong><span>Professional strategy summaries appear here.</span></div>}</section>{isOwner && <aside className="pn-asset-publisher"><header><Send size={14} /><strong>Publish Asset</strong></header><label>Type<select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="indicator">Indicator</option><option value="strategy">Strategy</option></select></label><label>Name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Description<textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label>{type === "indicator" ? <label>Version<input value={draft.version} onChange={(event) => setDraft({ ...draft, version: event.target.value })} /></label> : <><label>Market<input value={draft.market} onChange={(event) => setDraft({ ...draft, market: event.target.value })} /></label><label>Timeframe<input value={draft.timeframe} onChange={(event) => setDraft({ ...draft, timeframe: event.target.value })} /></label><label>Risk Profile<select value={draft.riskProfile} onChange={(event) => setDraft({ ...draft, riskProfile: event.target.value })}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option><option value="custom">Custom</option></select></label></>}<label>Visibility<select value={draft.visibility} onChange={(event) => setDraft({ ...draft, visibility: event.target.value })}><option value="public">Public</option><option value="followers">Followers</option><option value="private">Private</option></select></label><button type="button" className="primary" disabled={!draft.name.trim() || !draft.description.trim()} onClick={publish}>Publish {type}</button>{status && <div className="pn-form-status">{status}</div>}</aside>}</div>;
}

function AssetCard({ asset, type }: { asset: Record<string, unknown>; type: string }) {
  return <article className="pn-asset-card"><div><span>{type}</span><strong>{String(asset.name || "Untitled")}</strong></div><p>{String(asset.description || "No description published.")}</p><footer><em>{asset.version ? `Version ${String(asset.version)}` : `${String(asset.market || "Market")} · ${String(asset.timeframe || "Multiple")}`}</em><b>{String(asset.visibility || "public").toUpperCase()}</b></footer></article>;
}
