import type {
  AdaptiveSwingStrategySettings,
  IndicatorAdvancedSettings,
  OscillatorPaneSettings,
  QalcIndicatorSettings,
  VolumeProfileSettings,
  VwapSettings,
  WaveTrendOscillatorSettings,
  ZScoreOscillatorSettings
} from "../types.ts";
import { DEFAULT_LIQUIDATION_FIELD_SETTINGS } from "../../modules/liquidation-field/core/settings.ts";
import { DEFAULT_DDA_PRO_SETTINGS } from "../../modules/dda-pro/core/settings.ts";
import { DEFAULT_ACVD_SETTINGS } from "../../modules/acvd/core/settings.ts";
import { DEFAULT_CVD_OSCILLATOR_SETTINGS } from "../../modules/cvd-oscillator/core/settings.ts";

export const defaultVolumeProfileSettings: VolumeProfileSettings = {
  showVolumeProfile: true,
  upVolumeColor: "#30333a",
  downVolumeColor: "#9e9e9e",
  valueAreaUpColor: "#8a8a8a",
  valueAreaDownColor: "#5a0707",
  showSentimentProfile: true,
  sentimentBullishColor: "#d7d7d7",
  sentimentBearishColor: "#d40000",
  showSupplyDemandZones: true,
  supplyDemandThreshold: 15,
  supplyZoneColor: "#5d0808",
  demandZoneColor: "#2b2d31",
  supplyDemandIntensity: 60,
  showProfileGaps: true,
  nodeDetectionPercent: 7,
  profileGapColor: "#4c2b00",
  profileGapIntensity: 78,
  pocMode: "lastLine",
  pocColor: "#ff101b",
  pocWidth: 5,
  valueAreaPercent: 68,
  showVAH: true,
  vahColor: "#ff3046",
  vahWidth: 1,
  showVAL: true,
  valColor: "#bfbfbf",
  valWidth: 1,
  polarityMethod: "barPolarity",
  rangeMode: "fixed",
  fixedRangeLength: 5000,
  fixedRangeResetToken: 0,
  showProfileStats: true,
  statsSize: "Small",
  statsPosition: "Top Right",
  showPriceLevels: true,
  priceLabelSize: "Small",
  placement: "right",
  rows: 100,
  widthPercent: 31,
  horizontalOffset: 13,
  showValueAreaBackground: false,
  valueAreaBackgroundColor: "#2962ff",
  showProfileBackground: false,
  profileBackgroundColor: "#2962ff",
  hdlxOscillator: true,
  hdlxPriceSource: "hl2",
  hdlxLookback: 360,
  hdlxSmooth: 21,
  hdlxPreset: "Custom",
  hdlxExtreme: 3,
  hdlxClamp: 4,
  hdlxColorPreset: "Custom",
  hdlxPositiveColor: "#9f1d27",
  hdlxNegativeColor: "#bfbfbf",
  hdlxUseCustomLineColor: true,
  hdlxLineColor: "#ff101b",
  hdlxLineWidth: 1,
  hdlxFillTransparency: 83,
  hdlxHeight: 12.5,
  hdlxOffset: 3.5,
  hdlxDrawLevels: true,
  hdlxShowBackground: true,
  hdlxBackgroundColor: "#000000",
  hdlxEnableBarColoring: true,
  volumeWeightedBarColoring: false,
  volumeMaLength: 21,
  upperThreshold: 1.618,
  lowerThreshold: 0.618,
  strongBarUpColor: "#006400",
  strongBarDownColor: "#910000",
  weakBarUpColor: "#7fffd4",
  weakBarDownColor: "#ff9800"
};

export const defaultAdaptiveSwingStrategySettings: AdaptiveSwingStrategySettings = {
  showSignals: true,
  showSignalLabels: true,
  showTakeProfits: true,
  showStopLosses: false,
  showRegimeEma: true,
  showSwingLevels: true,
  showChopFilter: true,
  markerSize: 6,
  projectionBars: 10,
  labelSize: "Tiny",
  longColor: "#46b866",
  shortColor: "#ff303d",
  takeProfitColor: "#46b866",
  stopLossColor: "#8d929a",
  regimeEmaColor: "#ff303d",
  swingLevelColor: "#f59f18",
  swingLookback: 36,
  atrLength: 21,
  regimeEmaLength: 200,
  rsiLength: 14,
  rsiOversold: 42,
  rsiOverbought: 58,
  atrStopMultiplier: 1.55,
  swingRetestAtr: 0.8,
  stopLossPercent: 0.85,
  takeProfitRatio: 2.1,
  minTrendQuality: 0.16,
  maxChopRatio: 0.24,
  volumeLookback: 50,
  minVolumeMultiplier: 0.5,
  optimizationEnabled: true,
  optimizeSwingLookbackMin: 16,
  optimizeSwingLookbackMax: 40,
  optimizeSwingLookbackStep: 4,
  optimizeAtrStopMin: 1,
  optimizeAtrStopMax: 2.2,
  optimizeAtrStopStep: 0.2,
  optimizeTakeProfitMin: 1.2,
  optimizeTakeProfitMax: 3.5,
  optimizeTakeProfitStep: 0.4,
  optimizeTrendQualityMin: 0.08,
  optimizeTrendQualityMax: 0.46,
  optimizeTrendQualityStep: 0.03,
  robustnessMode: "Balanced"
};

export const defaultOscillatorPaneSettings: OscillatorPaneSettings = {
  height: 128,
  paneHeights: {
    openInterestOscillator: 128,
    zScoreOscillator: 128,
    waveTrendOscillator: 128,
    ddaProOscillator: 176,
    acvdOscillator: 176,
    cvdOscillator: 176
  },
  customPaneHeights: {},
  order: [],
  backgroundColor: "#000000",
  backgroundIntensity: 62,
  zeroLineColor: "#b8b8bc",
  zeroLineIntensity: 24
};

export const defaultWaveTrendOscillatorSettings: WaveTrendOscillatorSettings = {
  injectIntoPrimary: false,
  mainLineWidth: 1.35,
  signalLineWidth: 1,
  signalColor: "#777b83",
  signalIntensity: 46
};

export const defaultZScoreOscillatorSettings: ZScoreOscillatorSettings = {
  source: "close",
  calculationMethod: "price",
  basisMethod: "sma",
  deviationMode: "population",
  smoothingMethod: "ema",
  smoothingLength: 3,
  upperBand: 2,
  lowerBand: -2,
  clamp: 5,
  upperBandColor: "#b40020",
  lowerBandColor: "#d7d7da",
  midlineColor: "#8a8a90",
  lineWidth: 1.35,
  lineIntensity: 82,
  bandIntensity: 72,
  showBandFill: true,
  bandFillIntensity: 9
};

export const defaultVwapSettings: VwapSettings = {
  preset: "Institutional Session",
  anchorMode: "session",
  source: "hlc3",
  weightingModel: "volume",
  sessionAnchorHourUtc: 0,
  lookbackBars: 250,
  anchorLookbackBars: 500,
  atrLength: 21,
  decayHalfLife: 72,
  directionalBias: 1.25,
  regimeSensitivity: 2.2,
  volumeThreshold: 1.8,
  minimumBarsBetweenAnchors: 24,
  smoothingMethod: "none",
  smoothingLength: 3,
  bandMode: "weightedStd",
  bandPercentage: 0.75,
  showBand1: true,
  showBand2: true,
  showBand3: false,
  band1Multiplier: 1,
  band2Multiplier: 2,
  band3Multiplier: 3,
  band1Color: "#b9bdc5",
  band2Color: "#6d7078",
  band3Color: "#3d4047",
  bandIntensity: 42,
  showBandFill: true,
  bandFillColor: "#5b0712",
  bandFillIntensity: 5,
  lineWidth: 1.5,
  useCustomLineColor: false,
  lineColor: "#f1f1f3",
  dynamicSlopeColor: false,
  bullishColor: "#f1f1f3",
  bearishColor: "#d30024",
  neutralColor: "#94979e",
  slopeLookback: 5,
  slopeThresholdBps: 0.35,
  showAnchorMarkers: true,
  anchorMarkerColor: "#ff1738",
  showPreviousVwap: true,
  previousVwapColor: "#7f828a",
  previousVwapIntensity: 28
};

export const defaultQalcIndicatorSettings: QalcIndicatorSettings = {
  schemaVersion: 1,
  modelVersion: "BC-QALC-BASELINE-1",
  displayMode: "COMBINED",
  predictionHorizonMs: 1000,
  minimumNetEdgeMultiplier: 2,
  minimumFillProbability: 0.35,
  maximumToxicity: 44,
  quoteLifetimeMs: 500,
  showCandidates: true,
  showRejected: false,
  showQuotes: true,
  showCancellations: true,
  showPartialFills: true,
  showEntries: true,
  showExits: true,
  showMicrostructurePane: true,
  markerSize: 7,
  paneHeight: 78,
  paneScale: 1,
  paneOffset: 0,
  longColor: "#f2f2f4",
  shortColor: "#d00024",
  neutralColor: "#7f838a",
  tooltipDetail: "FULL",
  selectedRunId: ""
};

export const defaultIndicatorAdvancedSettings: IndicatorAdvancedSettings = {
  qalc: defaultQalcIndicatorSettings,
  liquidationField: DEFAULT_LIQUIDATION_FIELD_SETTINGS,
  volumeProfile: defaultVolumeProfileSettings,
  adaptiveSwingStrategy: defaultAdaptiveSwingStrategySettings,
  oscillatorPane: defaultOscillatorPaneSettings,
  zScoreOscillator: defaultZScoreOscillatorSettings,
  waveTrendOscillator: defaultWaveTrendOscillatorSettings,
  ddaProOscillator: DEFAULT_DDA_PRO_SETTINGS,
  acvdOscillator: DEFAULT_ACVD_SETTINGS,
  cvdOscillator: DEFAULT_CVD_OSCILLATOR_SETTINGS,
  vwap: defaultVwapSettings
};
