import { AlertTriangle, CheckCircle2, Play, Save, ShieldCheck } from "lucide-react";
import type { StrategyWizardDraft } from "../state/strategyDraftStore";
import { draftChanges, validateWizardStep } from "../state/strategyDraftStore";

export function ReviewStep({ draft, publishedName, publishedDefinition, saving, demoConnectionReady, onSaveDraft, onActivate }: { draft: StrategyWizardDraft; publishedName?: string; publishedDefinition?: StrategyWizardDraft["definition"] | null; saving: boolean; demoConnectionReady: boolean; onSaveDraft: () => void; onActivate: () => void }) {
  const issues = [...validateWizardStep(draft, 9), ...(demoConnectionReady ? [] : ["Connect and verify a Bybit Demo Trading account before activation."])];
  const changes = draftChanges(draft, publishedName, publishedDefinition);
  const published = draft.publishedVersion;
  const running = draft.runningVersion;
  return <div className="strategy-wizard-section"><header><span>10</span><div><h2>Activate Strategy &amp; Save Configuration</h2><p>This saves the draft, creates an immutable private configuration, starts the VPS runtime and arms the verified Bybit Demo target. It does not publish anything publicly.</p></div></header>
    <div className="version-state-grid"><Version label="CURRENT CONFIGURATION" value={`V${published ? published + 1 : 1}`} detail={`${changes.length} configuration change${changes.length === 1 ? "" : "s"}`} active /><Version label="SAVED VERSION" value={published ? `V${published}` : "NOT SAVED"} detail="Immutable after activation" /><Version label="ACTIVE VERSION" value={running ? `V${running}` : "NOT ACTIVE"} detail={running === published && running ? "VPS runtime synchronized" : "Activation will start this version"} /></div>
    <div className="review-summary-grid"><Summary label="NAME" value={draft.name || "—"} /><Summary label="INDICATOR" value={draft.definition.indicator?.name || "—"} /><Summary label="SYMBOL" value={draft.definition.symbol} /><Summary label="TIMEFRAME" value={draft.definition.timeframe.toUpperCase()} /><Summary label="MARKET" value={draft.definition.marketType} /><Summary label="ENTRY MAPPINGS" value={mappingSummary(draft)} /><Summary label="ALLOCATION" value={`${draft.paperPolicy.strategyAllocationValue}${draft.paperPolicy.strategyAllocationMode === "FIXED_USDT" ? " USDT" : "%"}`} /><Summary label="PER TRADE" value={`${draft.paperPolicy.tradeAmountValue}${draft.paperPolicy.tradeAmountMode === "FIXED_USDT" ? " USDT" : "%"}`} /><Summary label="LEVERAGE" value={draft.definition.marketType === "FUTURES" ? `${draft.paperPolicy.requestedLeverage || 1}x` : "SPOT 1x"} /><Summary label="EXECUTION TARGET" value="BYBIT DEMO · SIMULATED FUNDS" /></div>
    <section className="version-diff"><h3>{changes.length} DRAFT CHANGES</h3>{changes.map((change) => <div key={change.label}><strong>{change.label}</strong><span>{display(change.before)}</span><b>→</b><span>{display(change.after)}</span></div>)}</section>
    <section className="validation-summary"><h3>ACTIVATION VALIDATION</h3>{issues.length ? issues.map((issue) => <div className="blocked" key={issue}><AlertTriangle size={13} /><span>{issue}</span></div>) : <><div className="ready"><CheckCircle2 size={14} /><span>Indicator runtime, closed-candle market data, signal mapping, risk policy and Bybit Demo connection are ready.</span></div><div className="ready"><ShieldCheck size={14} /><span>Execution is isolated to simulated funds; real-funds Mainnet, withdrawals and transfers remain prohibited.</span></div></>}</section>
    <div className="review-actions"><button type="button" disabled={saving} onClick={onSaveDraft}><Save size={14} /> SAVE DRAFT ONLY</button><button type="button" className="primary" disabled={saving || issues.length > 0} onClick={onActivate}><Play size={14} /> ACTIVATE STRATEGY &amp; SAVE CONFIGURATION</button></div>
  </div>;
}

function Version({ label, value, detail, active }: { label: string; value: string; detail: string; active?: boolean }) { return <div className={active ? "active" : ""}><span>{label}</span><strong>{value}</strong><em>{detail}</em></div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function mappingSummary(draft: StrategyWizardDraft) { const signal = draft.definition.signals || {}; return draft.definition.marketType === "SPOT" ? `${signal.buyEntry || "—"} / ${signal.sellExit || "—"}` : `${signal.longEntry || "—"} / ${signal.shortEntry || "—"}`; }
function display(value: string) { return value.length > 80 ? `${value.slice(0, 77)}…` : value; }
