import { AlertTriangle, CheckCircle2, ShieldCheck } from "lucide-react";
import type { StrategyWizardDraft } from "../state/strategyDraftStore";
import { draftChanges, validateWizardStep } from "../state/strategyDraftStore";

export function ReviewStep({ draft, publishedName, publishedDefinition }: { draft: StrategyWizardDraft; publishedName?: string; publishedDefinition?: StrategyWizardDraft["definition"] | null }) {
  const issues = validateWizardStep(draft, 3);
  const changes = draftChanges(draft, publishedName, publishedDefinition);
  const published = draft.publishedVersion;
  const running = draft.runningVersion;
  const certified = draft.definition.indicator?.runtimeStatus === "CERTIFIED";
  return <div className="strategy-wizard-section"><header><span>04</span><div><h2>Save strategy</h2><p>Create the private algorithm first. Broker connections, Investment Groups, sizing, leverage and arming are configured only after it opens inside Strategy Lab.</p></div></header>
    <div className="version-state-grid"><Version label="CURRENT CONFIGURATION" value={`V${published ? published + 1 : 1}`} detail={`${changes.length} configuration change${changes.length === 1 ? "" : "s"}`} active /><Version label="SAVED VERSION" value={published ? `V${published}` : "NOT SAVED"} detail="Private and immutable when published" /><Version label="ACTIVE VERSION" value={running ? `V${running}` : "NOT ACTIVE"} detail={certified ? "Paper runtime starts after save" : "Awaiting VPS certification"} /></div>
    <div className="review-summary-grid"><Summary label="STRATEGY" value={draft.name || "—"} /><Summary label="SIGNAL SOURCE" value={draft.definition.indicator?.name || "—"} /><Summary label="CURRENCY" value={draft.definition.symbol} /><Summary label="TIMEFRAME" value={draft.definition.timeframe.toUpperCase()} /><Summary label="MARKET" value={draft.definition.marketType} /><Summary label="BROKER COMMANDS" value={draft.definition.marketType === "SPOT" ? "BUY / SELL OWNED ASSET" : "OPEN / CLOSE LONG & SHORT"} /><Summary label="ENTRY MAPPINGS" value={mappingSummary(draft)} /><Summary label="STOP OVERRIDE" value={draft.definition.execution.stopLossEnabled === true ? `${String(draft.definition.execution.longStopMode || "PRICE_PERCENT")} · ${String(draft.definition.execution.longStopValue || "—")}` : "SCRIPT NATIVE"} /><Summary label="REVERSAL" value={draft.definition.marketType === "SPOT" ? "NOT AVAILABLE ON SPOT" : `${draft.definition.execution.stopReversalEnabled === true ? "REVENGE ON" : "REVENGE OFF"} · ${draft.definition.execution.perpetualSignalReversalEnabled === true ? "PERPETUAL ON" : "PERPETUAL OFF"}`} /></div>
    <section className="version-diff"><h3>{changes.length} DRAFT CHANGES</h3>{changes.map((change) => <div key={change.label}><strong>{change.label}</strong><span>{display(change.before)}</span><b>→</b><span>{display(change.after)}</span></div>)}</section>
    <section className="validation-summary"><h3>SAVE VALIDATION</h3>{issues.length ? issues.map((issue) => <div className="blocked" key={issue}><AlertTriangle size={13} /><span>{issue}</span></div>) : <><div className="ready"><CheckCircle2 size={14} /><span>Strategy selection, currency, timeframe and signal mapping are complete.</span></div><div className="ready"><ShieldCheck size={14} /><span>No broker or Investment Group is connected by this wizard. Live execution remains unarmed until you add and approve it from LIVE TARGETS.</span></div>{!certified ? <div className="blocked"><AlertTriangle size={13} /><span>The strategy will be saved with its native settings, but Paper and live execution remain locked until its VPS runtime is certified.</span></div> : null}</>}</section>
  </div>;
}

function Version({ label, value, detail, active }: { label: string; value: string; detail: string; active?: boolean }) { return <div className={active ? "active" : ""}><span>{label}</span><strong>{value}</strong><em>{detail}</em></div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function mappingSummary(draft: StrategyWizardDraft) { const signal = draft.definition.signals || {}; return draft.definition.marketType === "SPOT" ? `${signal.buyEntry || "—"} / ${signal.sellExit || "—"}` : `${signal.longEntry || "—"} / ${signal.shortEntry || "—"}`; }
function display(value: string) { return value.length > 80 ? `${value.slice(0, 77)}…` : value; }
