import type { ReactNode } from "react";
import type { StrategyTradeAmountMode } from "../../automation/strategyAutomation.types";
import type { StrategyWizardDraft } from "../state/strategyDraftStore";
import { NumberField } from "./ExecutionStep";

export function RiskStep({ draft, onChange }: { draft: StrategyWizardDraft; onChange: (draft: StrategyWizardDraft) => void }) {
  const policy = draft.paperPolicy;
  const execution = draft.definition.execution;
  const patchPolicy = (key: keyof typeof policy, value: unknown) => onChange({ ...draft, paperPolicy: { ...policy, [key]: value } });
  const patchExecution = (key: string, value: unknown) => onChange({ ...draft, definition: { ...draft.definition, execution: { ...execution, [key]: value } } });
  const patchPolicyAndExecution = (policyKey: keyof typeof policy, executionKey: string, value: unknown) => onChange({
    ...draft,
    paperPolicy: { ...policy, [policyKey]: value },
    definition: { ...draft.definition, execution: { ...execution, [executionKey]: value } },
  });
  const equity = Number(draft.definition.paper?.demoEquity || 10_000);
  const allocation = policy.strategyAllocationMode === "FIXED_USDT" ? Math.min(equity, policy.strategyAllocationValue) : equity * policy.strategyAllocationValue / 100;
  const perTrade = ["PERCENT_ACCOUNT_EQUITY"].includes(policy.tradeAmountMode) ? equity * policy.tradeAmountValue / 100 : ["FIXED_USDT", "FIXED_QUANTITY"].includes(policy.tradeAmountMode) ? policy.tradeAmountValue : allocation * policy.tradeAmountValue / 100;
  const leverage = draft.definition.marketType === "FUTURES" ? policy.requestedLeverage || 1 : 1;
  return <div className="strategy-wizard-section">
    <header><span>05</span><div><h2>Risk management</h2><p>Capital allocation, per-trade risk and suspension limits are separate controls.</p></div></header>
    <Section title="POSITION SIZING"><div className="strategy-form-grid"><label>STRATEGY ALLOCATION MODE<select value={policy.strategyAllocationMode} onChange={(event) => patchPolicy("strategyAllocationMode", event.target.value)}><option value="PERCENT_ACCOUNT_EQUITY">Percentage of Account Equity</option><option value="FIXED_USDT">Fixed USDT Amount</option></select></label><NumberField label="STRATEGY ALLOCATION" value={policy.strategyAllocationValue} suffix={policy.strategyAllocationMode === "FIXED_USDT" ? "USDT" : "%"} min={0.1} step={0.1} onChange={(value) => patchPolicy("strategyAllocationValue", value)} /><label>TRADE AMOUNT MODE<select value={policy.tradeAmountMode} onChange={(event) => patchPolicy("tradeAmountMode", event.target.value as StrategyTradeAmountMode)}>{tradeModes.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><NumberField label="PER-TRADE AMOUNT" value={policy.tradeAmountValue} suffix={["FIXED_USDT"].includes(policy.tradeAmountMode) ? "USDT" : policy.tradeAmountMode === "FIXED_QUANTITY" ? "QTY" : "%"} min={0.01} step={0.01} onChange={(value) => patchPolicy("tradeAmountValue", value)} /><NumberField label="MAXIMUM POSITION SIZE" value={policy.maximumPositionPercent} suffix="%" min={0} max={100} onChange={(value) => patchPolicy("maximumPositionPercent", value)} /><NumberField label="MAXIMUM TOTAL EXPOSURE" value={policy.maximumExposurePercent} suffix="%" min={0} max={100} onChange={(value) => patchPolicy("maximumExposurePercent", value)} /></div></Section>
    {draft.definition.marketType === "FUTURES" ? <Section title="FUTURES LEVERAGE"><div className="strategy-form-grid"><NumberField label="REQUESTED LEVERAGE" value={policy.requestedLeverage || 1} suffix="x" min={1} max={100} onChange={(value) => patchPolicy("requestedLeverage", value)} /><NumberField label="MAXIMUM ALLOWED LEVERAGE" value={policy.maximumLeverage || 1} suffix="x" min={1} max={100} onChange={(value) => patchPolicyAndExecution("maximumLeverage", "maxLeverage", value)} /><label>MARGIN MODE<select value={policy.marginMode || "CROSS"} onChange={(event) => patchPolicy("marginMode", event.target.value)}><option value="CROSS">Cross</option><option value="ISOLATED">Isolated</option></select></label></div></Section> : null}
    <Section title="STOP LOSS"><div className="strategy-form-grid"><label>{draft.definition.marketType === "FUTURES" ? "LONG STOP LOSS" : "BUY POSITION STOP LOSS"}<select value={String(execution.longStopMode || "PRICE_PERCENT")} onChange={(event) => patchExecution("longStopMode", event.target.value)}>{stopModes.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><NumberField label="LONG / BUY STOP VALUE" value={Number(execution.longStopValue || draft.definition.settings.stopLossPercent || 1)} suffix="%" min={0.01} step={0.01} onChange={(value) => patchExecution("longStopValue", value)} />{draft.definition.marketType === "FUTURES" ? <><label>SHORT STOP LOSS<select value={String(execution.shortStopMode || "PRICE_PERCENT")} onChange={(event) => patchExecution("shortStopMode", event.target.value)}>{stopModes.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><NumberField label="SHORT STOP VALUE" value={Number(execution.shortStopValue || draft.definition.settings.stopLossPercent || 1)} suffix="%" min={0.01} step={0.01} onChange={(value) => patchExecution("shortStopValue", value)} /></> : null}</div></Section>
    <Section title="GLOBAL LIMITS"><div className="strategy-form-grid"><NumberField label="MAXIMUM DAILY LOSS" value={Number(execution.maxDailyLoss || policy.maximumDailyLoss)} suffix="USDT" min={1} onChange={(value) => patchPolicyAndExecution("maximumDailyLoss", "maxDailyLoss", value)} /><NumberField label="MAXIMUM STRATEGY DRAWDOWN" value={Number(execution.maxDrawdown || policy.maximumDrawdown)} suffix="%" min={0.1} max={100} step={0.1} onChange={(value) => patchPolicyAndExecution("maximumDrawdown", "maxDrawdown", value)} /><NumberField label="MAXIMUM CONSECUTIVE LOSSES" value={Number(execution.maximumConsecutiveLosses || 3)} min={1} onChange={(value) => patchExecution("maximumConsecutiveLosses", value)} /><NumberField label="MAXIMUM OPEN POSITIONS" value={Number(execution.maxOpenPositions || policy.maximumPositions)} min={1} onChange={(value) => patchPolicyAndExecution("maximumPositions", "maxOpenPositions", value)} /><NumberField label="MAXIMUM TRADES / DAY" value={Number(execution.maxTradesPerDay || 8)} min={1} onChange={(value) => patchExecution("maxTradesPerDay", value)} /></div><p className="risk-consequence">Daily loss, drawdown and consecutive-loss limits suspend new entries. Stop-loss and liquidation protection may close existing positions.</p></Section>
    <div className="capital-preview"><span>CAPITAL PREVIEW</span><div><b>Paper equity</b><strong>{money(equity)}</strong></div><div><b>Allocated capital</b><strong>{money(allocation)}</strong></div><div><b>Per-trade capital</b><strong>{money(perTrade)}</strong></div><div><b>Requested leverage</b><strong>{leverage}x</strong></div><div><b>Estimated notional</b><strong>{money(perTrade * leverage)}</strong></div></div>
  </div>;
}

const tradeModes: string[][] = [["PERCENT_ACCOUNT_EQUITY", "Percentage of Account Equity"], ["PERCENT_STRATEGY_ALLOCATION", "Percentage of Strategy Allocation"], ["RISK_PERCENT", "Risk Percentage Per Trade"], ["FIXED_USDT", "Fixed USDT Amount"], ["FIXED_QUANTITY", "Fixed Quantity"], ["VOLATILITY_TARGET", "Volatility Target"]];
const stopModes: string[][] = [["FIXED_USDT", "Fixed USDT Loss"], ["ENTRY_PERCENT", "Percentage of Entry Capital"], ["EQUITY_PERCENT", "Percentage of Account Equity"], ["PRICE_PERCENT", "Price Percentage"], ["ATR_MULTIPLE", "ATR Multiple"], ["INDICATOR_ALERT", "Indicator Alert"], ["STRUCTURE_LEVEL", "Structure Level"]];
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="wizard-risk-section"><h3>{title}</h3>{children}</section>; }
function money(value: number) { return `$${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
