import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const read = (path: string) => readFileSync(resolve(root, path), "utf8");

const secureClient = read("src/core/secureCredentialStore.ts");
const vault = read("src-tauri/src/credential_vault.rs");
const localRuntime = read("src-tauri/src/local_runtime.rs");
const nativeShell = read("src-tauri/src/lib.rs");
const tauriConfig = JSON.parse(read("src-tauri/tauri.conf.json"));
const bootstrap = read("src/components/StandaloneBootstrap.tsx");
const app = read("src/App.tsx");
const multiChart = read("src/components/MultiChartWorkspace.tsx");
const chart = read("src/components/PixiBlackChart.tsx");
const engine = read("src/chart-engine/BlackChartEngine.ts");
const localStore = read("src-tauri/src/local_store.rs");
const localCrypto = read("src-tauri/src/local_crypto.rs");
const localExecution = read("src-tauri/src/local_execution.rs");
const localBybit = read("src-tauri/src/bybit_local.rs");
const localP2p = read("src-tauri/src/local_p2p.rs");
const localP2pClient = read("src/core/local-runtime/localP2pClient.ts");
const localAi = read("src-tauri/src/local_ai.rs");
const localAiClient = read("src/core/local-runtime/localAiClient.ts");
const blackGpt = read("src/components/BlackGPT.tsx");
const portfolioApi = read("src/portfolio/portfolioApiClient.ts");
const profileMigration = read("src/core/local-runtime/profileMigration.ts");
const localBrokerStore = read("src/core/local-runtime/localBrokerStore.ts");
const localStrategyStore = read("src/core/local-runtime/localStrategyStore.ts");
const localStrategyApi = read("src/modules/strategy-lab/automation/strategyAutomationApi.ts");
const localStrategyCoordinator = read("src/core/local-runtime/localStrategyCoordinator.ts");
const localUserScripts = read("src/core/local-runtime/localUserScriptStore.ts");
const localGroupMandates = read("src/core/local-runtime/localInvestmentGroupMandateStore.ts");
const localGroupRemote = read("src/core/local-runtime/localInvestmentGroupRemoteStore.ts");
const localGroupP2p = read("src/core/local-runtime/localInvestmentGroupP2pCoordinator.ts");
const localP2pOutbox = read("src/core/local-runtime/localP2pOutbox.ts");
const localAlertOutbox = read("src/core/local-runtime/localAlertDeliveryOutbox.ts");
const immDepthHistory = read("src/modules/dom-pro/depthHistoryStore.ts");
const immWorkspace = read("src/modules/dom-pro/components/DomProWindow.tsx");
const localLiquidity = read("src/modules/dom-pro/consolidatedLiquidityClient.ts");
const eventAlphaApi = read("src/modules/event-alpha/eventAlphaApi.ts");
const qalcApi = read("src/modules/strategy-lab/qalc/qalcApi.ts");
const localQalcRuntime = read("src/modules/strategy-lab/qalc/localQalcRuntime.ts");
const qalcEngine = read("server/qalc/engine.ts");
const qalcPaperBroker = read("server/qalc/paper-broker.ts");
const releaseManifest = read("scripts/generate-standalone-release-manifest.mjs");
const professionalNetwork = read("src/modules/professional-network/localProfessionalNetworkApi.ts");
const networkApi = read("src/modules/professional-network/networkApi.ts");
const settingsPanel = read("src/components/SettingsPanel.tsx");
const institutionalFlow = read("src/institutional-flow/institutionalFlowClient.ts");
const persistentAuthenticFlow = read("src/modules/acvd/data/persistentFlowClient.ts");
const liquidationController = read("src/modules/liquidation-field/data/LiquidationFieldController.ts");
const indicatorLibrary = read("src/components/IndicatorLibrary.tsx");
const releaseWorkflow = read("../.github/workflows/standalone-release.yml");
const standaloneStyles = read("src/styles/standalone-bootstrap.css");
const resend = read("src/lib/resend.ts");

assert.match(secureClient, /return await invoke<StoredCredentialReference>\("secure_store_exchange_credentials"/);
assert.doesNotMatch(secureClient, /catch\s*\([^)]*\)[\s\S]{0,300}storedAt:\s*Date\.now/);
assert.match(vault, /keyring::Entry::new\(VAULT_SERVICE, vault_key\)/);
assert.match(vault, /Zeroizing::new/);
assert.match(vault, /credential-index-v1\.json/);
assert.doesNotMatch(vault, /pub\(crate\) async fn secure_(?:get|read|load)_exchange/);
assert.doesNotMatch(nativeShell, /secure_(?:get|read|load)_exchange_credentials/);

assert.match(localRuntime, /P2P_IDENTITY_VAULT_KEY/);
assert.match(localRuntime, /pub\(crate\) struct UpdateLocalRuntimeRequest/);
assert.match(localRuntime, /config\.background_execution = request\.background_execution/);
assert.match(nativeShell, /local_runtime::update_local_runtime/);
assert.match(localRuntime, /\("ios", false,/);
assert.match(localRuntime, /\("android", false,/);
assert.match(localRuntime, /cannot be certified as an always-on trading host/);
assert.match(nativeShell, /"Open Black Terminal"/);
assert.match(nativeShell, /"Open Settings"/);
assert.match(nativeShell, /"Quit Black Terminal"/);
assert.match(nativeShell, /WindowEvent::CloseRequested/);
assert.match(nativeShell, /api\.prevent_close\(\)/);
assert.match(nativeShell, /show_menu_on_left_click\(true\)/);
assert.match(nativeShell, /start_local_runtime_watchdog/);
assert.match(localRuntime, /STRATEGY_HOST_DEGRADED/);
assert.match(localRuntime, /EXECUTION_WORKER_DEGRADED/);
assert.match(bootstrap, /black-terminal-local-strategy-host/);
assert.match(bootstrap, /sendLocalRuntimeHeartbeat/);
assert.match(localStore, /PRAGMA journal_mode=WAL/);
assert.match(localStore, /encrypt_local_text\(&format!\("document:/);
assert.match(localCrypto, /Aes256Gcm/);
assert.match(localCrypto, /Payload \{/);
assert.match(localCrypto, /aad: purpose\.as_bytes\(\)/);
assert.match(localCrypto, /internal:local-data-master:v1/);
assert.match(localExecution, /idempotency_key TEXT NOT NULL UNIQUE/);
assert.match(localExecution, /CREATE TABLE IF NOT EXISTS local_execution_dependencies/);
assert.match(localExecution, /parent\.status <> 'SUCCEEDED'/);
assert.match(localExecution, /LOCAL_EXECUTION_IDEMPOTENCY_COLLISION/);
assert.match(localExecution, /Broker secrets are forbidden in the durable execution queue/);
assert.match(localExecution, /execution-payload:/);
assert.match(localExecution, /execution-result:/);
assert.match(localExecution, /status='IN_FLIGHT', attempts=attempts\+1/);
assert.match(localExecution, /bybit_local_place_partial_take_profits/);
assert.match(localExecution, /bybit_local_reverse_position/);
assert.match(localBybit, /\/v5\/user\/query-api/);
assert.match(localBybit, /find_order_by_link_id/);
assert.match(localBybit, /BYBIT_ORDER_FILL_UNCONFIRMED/);
assert.match(localBybit, /BYBIT_REVERSAL_DUPLICATE_TARGET/);
assert.match(localBybit, /existing_order_receipt/);
assert.match(localBybit, /\/v5\/order\/history/);
assert.match(localBybit, /SERVER_TIME_CACHE_MILLIS/);
assert.match(localBybit, /HTTP_CLIENT/);
assert.match(localBybit, /pub\(crate\) async fn bybit_local_clock_sample/);
assert.match(nativeShell, /bybit_local::bybit_local_clock_sample/);
assert.match(portfolioApi, /isLocalOnlyRuntime\(\)\) return submitLocalPortfolioOrder/);
assert.match(portfolioApi, /executionType: "ORDER"/);
assert.match(portfolioApi, /executionType: "LEVERAGE"/);
assert.match(portfolioApi, /if \(isLocalOnlyRuntime\(\)\) return localAccountSync/);
assert.match(portfolioApi, /executionType: "PROTECTION"/);
assert.match(portfolioApi, /Personal-chart broker accounts are isolated from Strategy Lab/);
assert.match(localBrokerStore, /status !== "DISCONNECTED"/);

assert.match(localP2p, /MessageAuthenticity::Signed/);
assert.match(localP2p, /noise::Config::new/);
assert.match(localP2p, /ValidationMode::Strict/);
assert.match(localP2p, /MDNS_LAN/);
assert.match(localP2p, /UPNP_PORT_MAPPING/);
assert.match(localP2p, /upnp::tokio::Behaviour/);
assert.match(localP2p, /TRUSTED_PEER_KADEMLIA_MESH/);
assert.match(localP2p, /kad::Behaviour<MemoryStore>/);
assert.match(localP2p, /black-terminal\/kad\/1/);
assert.match(localP2p, /identify::Event::Received/);
assert.match(localP2p, /symmetric NAT and restrictive firewalls/i);
assert.match(localP2pClient, /const TRUSTED_PEER_NAMESPACE = "p2p-network"/);
assert.match(localP2pClient, /listTrustedLocalP2pPeers/);
assert.match(localP2pClient, /Promise\.allSettled\(peers\.map/);
assert.match(localP2p, /encrypt_local_text\(&format!\("p2p-inbox:/);
assert.match(localP2p, /request_response::cbor::Behaviour/);
assert.match(localP2p, /black-terminal\/direct\/1/);
assert.match(nativeShell, /local_p2p::local_p2p_send_direct/);
assert.match(nativeShell, /local_p2p::local_p2p_stop/);
assert.match(nativeShell, /local_ai::local_ai_chat/);
assert.match(localAi, /matches!\(host\.as_str\(\), "127\.0\.0\.1" \| "::1"\)/);
assert.match(localAi, /redirect\(reqwest::redirect::Policy::none\(\)\)/);
assert.match(localAi, /MAX_AI_RESPONSE_BYTES/);
assert.match(localAi, /request\.messages\.len\(\) > 40/);
assert.match(localAiClient, /const NAMESPACE = "local-ai"/);
assert.match(localAiClient, /Use an explicit numeric loopback Ollama-compatible \/api\/chat endpoint/);
assert.match(blackGpt, /getLocalDocument<Message\[]>\("local-ai-chats"/);
assert.match(blackGpt, /requestLocalAiChat\(history/);
assert.doesNotMatch(blackGpt, /Gemini API handshake failed/);
assert.match(professionalNetwork, /kind: "direct-message"/);
assert.match(professionalNetwork, /sendLocalP2pDirect/);
assert.match(networkApi, /isLocalOnlyRuntime\(\) \? localProfessionalNetworkApi/);
assert.match(settingsPanel, /"settings", "alert-delivery"/);
assert.match(settingsPanel, /handleRuntimeSetting/);
assert.match(settingsPanel, /LOCAL BLACKGPT PROVIDER/);
assert.match(resend, /if \(isLocalOnlyRuntime\(\)\) return \{ success: false/);

assert.match(app, /currentUser\?\.role === "admin" && !isLocalOnlyRuntime\(\)/);
assert.match(institutionalFlow, /if \(isLocalOnlyRuntime\(\)\) throw new Error/);
assert.match(persistentAuthenticFlow, /if \(isLocalOnlyRuntime\(\)\) throw new Error/);
assert.match(liquidationController, /DEVICE_LOCAL_PUBLIC_MARKET_STREAM/);
assert.match(liquidationController, /if \(isLocalOnlyRuntime\(\)\) return/);
assert.match(indicatorLibrary, /const refreshed = isLocalOnlyRuntime\(\)/);

const nativeCsp = String(tauriConfig.app.security.csp || "");
assert.doesNotMatch(nativeCsp, /black-terminal\.live/);
assert.doesNotMatch(nativeCsp, /supabase\.co/);

assert.match(profileMigration, /PBKDF2/);
assert.match(profileMigration, /AES-GCM/);
assert.match(profileMigration, /KDF_ITERATIONS = 600_000/);
assert.doesNotMatch(profileMigration, /"bt_webhook_url"/);
assert.match(profileMigration, /"webhook secrets"/);

assert.match(localBrokerStore, /workspaceScope\?: "PERSONAL" \| "STRATEGY_LAB"/);
assert.match(localBrokerStore, /workspaceScope \|\| "PERSONAL"/);
assert.match(localStrategyStore, /listLocalBrokerAccounts\("STRATEGY_LAB"\)/);
assert.match(localStrategyStore, /at most nine active execution targets/);
assert.match(localStrategyStore, /activeLocalInvestmentGroupMandates/);
assert.match(localStrategyStore, /localStrategyGroupExecutionDesks/);
assert.match(localStrategyStore, /authenticated P2P member mandate/);
assert.match(localGroupMandates, /const MANDATE_NAMESPACE = "investment-group-mandates"/);
assert.match(localGroupMandates, /Membership never grants|Only an active group member/);
assert.match(localGroupMandates, /Withdrawal-enabled API keys cannot participate/);
assert.match(localGroupMandates, /maxStrategyAllocationPercent/);
assert.match(localGroupMandates, /maxPerTradeAllocationPercent/);
assert.match(localGroupMandates, /Mainnet authority is not confirmed/);
assert.match(localBrokerStore, /Investment Group execution mandate/);
assert.match(localStrategyApi, /isLocalOnlyRuntime\(\)/);
assert.match(localStrategyCoordinator, /evaluateBlackScriptCloudRuntime/);
assert.match(localStrategyCoordinator, /getLocalStrategyPaperRuntime/);
assert.match(localStrategyCoordinator, /paperMatchesExecution/);
assert.match(localStrategyCoordinator, /orderManifestCommands/);
assert.match(localStrategyCoordinator, /requireSucceededDependencies/);
assert.match(localStrategyCoordinator, /positionDirection === "long" \? "Sell"/);
assert.match(localStrategyCoordinator, /dependsOnIdempotencyKeys/);
assert.match(localStrategyCoordinator, /enqueueLocalExecution/);
assert.match(localStrategyCoordinator, /loadLocalUserScripts/);
assert.match(localStrategyCoordinator, /WAITING_FOR_BROKER_RECONCILIATION/);
assert.match(localStrategyCoordinator, /fetchStrategyLabIntrabars/);
assert.match(localStrategyCoordinator, /LOCAL_BAR_MAGNIFIER_COVERAGE_INCOMPLETE/);
assert.match(localStrategyCoordinator, /LOCAL_GROUP_MANDATE_PREFLIGHT_FAILED/);
assert.match(localStrategyCoordinator, /LOCAL_EXECUTION_ACCOUNT_BOUND_MORE_THAN_ONCE/);
assert.match(localStrategyCoordinator, /group-strategy-evaluation/);
assert.match(localStrategyCoordinator, /LOCAL_GROUP_REMOTE_ACK_PENDING/);
assert.match(localStrategyCoordinator, /executeRemoteInvestmentGroupEvaluation/);
assert.match(localGroupMandates, /publicMandateId/);
assert.match(localGroupMandates, /group-mandate-state/);
assert.doesNotMatch(localGroupMandates, /group-mandate-state[\s\S]{0,1000}accountId:/);
assert.match(localGroupRemote, /investment-group-remote-mandates/);
assert.match(localGroupRemote, /execution host is offline or not directly connected/);
assert.match(localGroupRemote, /investment-group-remote-receipts/);
assert.match(localGroupP2p, /group-join-request/);
assert.match(localGroupP2p, /group-strategy-ack/);
assert.match(localP2pOutbox, /const NAMESPACE = "p2p-direct-outbox"/);
assert.match(localP2pOutbox, /Broker secrets are forbidden in the P2P outbox/);
assert.match(localAlertOutbox, /const NAMESPACE = "alert-webhook-outbox"/);
assert.match(localAlertOutbox, /Broker secrets are forbidden in the alert delivery outbox/);
assert.match(localAlertOutbox, /2_000 \* \(2 \*\* Math\.min\(8, attempts\)\)/);
assert.match(localUserScripts, /const NAMESPACE = "user-scripts"/);
assert.match(localUserScripts, /putLocalDocument\(NAMESPACE/);
assert.match(localUserScripts, /localStorage\.removeItem\(legacyKey/);
assert.match(localStrategyStore, /const STRATEGY_PAPER_LEDGER_NAMESPACE = "strategy-paper-ledgers"/);
assert.match(localStrategyStore, /checkpoint: copy\(evaluation\.checkpoint\)/);
assert.match(localStrategyStore, /Pause Paper Trading before changing its virtual capital/);
assert.match(localStrategyStore, /Close the Paper position and cancel its working orders before reset/);
assert.match(localStrategyStore, /report\.endingEquity - usedStrategyCapital/);
assert.match(localStrategyStore, /currentDrawdownPercent: currentDrawdown/);
assert.match(localStrategyStore, /getLocalBrokerSymbolExposure/);
assert.match(localStrategyStore, /Strategy Lab never inherits manual exposure/);
assert.match(localStrategyCoordinator, /LOCAL_TARGET_PREEXISTING_SYMBOL_EXPOSURE/);

assert.match(immDepthHistory, /const localDocumentNamespace = "imm-depth-history"/);
assert.match(immDepthHistory, /hydrateEncryptedLocal/);
assert.match(immDepthHistory, /if \(!isLocalOnlyRuntime\(\)\) void this\.hydrateBlackCore/);
assert.match(immWorkspace, /workerStatus: worker\.running \? "local-worker" : "local-idle"/);
assert.match(immWorkspace, /ENCRYPTED LOCAL/);
assert.match(localLiquidity, /fetchLocalConsolidatedLiquidity/);
assert.match(localLiquidity, /black-terminal-local-liquidity-fabric/);
assert.match(localLiquidity, /\{ exchange: "bybit"/);
assert.match(localLiquidity, /\{ exchange: "binance"/);
assert.match(localLiquidity, /\{ exchange: "okx"/);
assert.match(eventAlphaApi, /architecture: "SERVER_AUTHORITY" \| "LOCAL_AUTHORITY"/);
assert.match(eventAlphaApi, /getLocalDocument<LocalEventAlphaState>\("event-alpha", "state"\)/);
assert.match(eventAlphaApi, /safe_error_code: "LOCAL_PROVIDER_REQUIRED"/);
assert.match(qalcApi, /const LOCAL_QALC_NAMESPACE = "qalc-strategies"/);
assert.match(qalcApi, /activateLocalQalcRuntime/);
assert.match(qalcApi, /getLocalQalcTimeline/);
assert.match(localQalcRuntime, /LOCAL_DEVICE_QALC_EVENT_ENGINE/);
assert.match(localQalcRuntime, /orderbook\.200\./);
assert.match(localQalcRuntime, /publicTrade\./);
assert.match(localQalcRuntime, /paperEnabled: true/);
assert.match(localQalcRuntime, /liveExecutionEnabled: false/);
assert.match(localQalcRuntime, /groupFanoutEnabled: false/);
assert.match(localQalcRuntime, /sampleLocalBybitClock/);
assert.match(localQalcRuntime, /MAX_TIMELINE_EVENTS = 5_000/);
assert.match(localQalcRuntime, /PAPER_CONSERVATIVE/);
assert.doesNotMatch(qalcEngine, /node:perf_hooks/);
assert.doesNotMatch(qalcPaperBroker, /node:crypto/);

assert.equal(tauriConfig.productName, "Black Terminal");
assert.equal(tauriConfig.version, "1.0.7");
assert.equal(tauriConfig.bundle.targets, "all");
assert.equal(tauriConfig.bundle.windows.nsis.installMode, "currentUser");
assert.equal(tauriConfig.bundle.windows.nsis.headerImage, "installer/nsis-header.bmp");
assert.equal(tauriConfig.bundle.windows.nsis.sidebarImage, "installer/nsis-sidebar.bmp");
assert.ok(existsSync(resolve(root, "src-tauri/installer/nsis-header.bmp")));
assert.ok(existsSync(resolve(root, "src-tauri/installer/nsis-sidebar.bmp")));
assert.ok(tauriConfig.bundle.icon.includes("icons/icon.icns"));
assert.ok(tauriConfig.bundle.icon.includes("icons/icon.ico"));
assert.ok(existsSync(resolve(root, "src-tauri/icons/icon.icns")));
assert.ok(existsSync(resolve(root, "src-tauri/icons/icon.ico")));
assert.match(releaseWorkflow, /windows-2022/);
assert.match(releaseWorkflow, /ubuntu-22\.04/);
assert.match(releaseWorkflow, /macos-14/);
assert.match(releaseWorkflow, /cargo test --locked/);
assert.match(releaseWorkflow, /Generate SHA-256 release manifest/);
assert.match(releaseManifest, /createHash\("sha256"\)/);

assert.match(bootstrap, /Local-only core/);
assert.match(bootstrap, /initializeLocalRuntime/);
assert.match(bootstrap, /persistentBackgroundSupported/);
assert.match(bootstrap, /standaloneSetupPreview/);
assert.match(standaloneStyles, /height: 100vh;/);
assert.match(standaloneStyles, /overflow: auto;/);
assert.match(standaloneStyles, /@media \(max-width: 780px\)[\s\S]*place-items: start center/);

assert.match(multiChart, /MAX_MULTI_CHART_PANES = 7/);
assert.match(multiChart, /symbolRaw: string/);
assert.match(multiChart, /timeframe: Timeframe/);
assert.match(multiChart, /visibleIndicators: VisibleIndicators/);
assert.match(multiChart, /indicatorAdvancedSettings: IndicatorAdvancedSettings/);
assert.match(multiChart, /bt_multi_chart_workspace_v1/);
assert.match(app, /renderSecondary=\{\(pane, paneSymbol, update\)/);
assert.match(app, /update\("visibleIndicators", value\)/);
assert.match(app, /Array\.from\(\{ length: 7 \}/);

assert.match(app, /renderingPreferences=\{chartRenderingPreferences\}/);
assert.match(chart, /renderingPreferences\?\.resolutionMode/);
assert.match(engine, /resolveChartDevicePreferences/);
assert.match(engine, /antialias: this\.rendererAntialias/);

console.log("Desktop local-runtime contracts passed: vault, SQLite, durable native Bybit execution, encrypted P2P, tray, onboarding, packaging, DPI, and seven independent chart panes.");
