import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8");
const tabs = read("src/modules/strategy-lab/components/StrategyTabs.tsx");
const page = read("src/modules/strategy-lab/components/StrategyLabPage.tsx");
const experience = read("src/modules/strategy-lab/my-strategy/StrategyAutomationExperience.tsx");
const library = read("src/modules/strategy-lab/my-strategy/pages/StrategyLibraryPage.tsx");
const wizard = read("src/modules/strategy-lab/my-strategy/pages/StrategyWizardPage.tsx");
const draftStore = read("src/modules/strategy-lab/my-strategy/state/strategyDraftStore.ts");
const indicator = read("src/modules/strategy-lab/my-strategy/wizard/IndicatorMarketStep.tsx");
const manifest = read("src/modules/strategy-lab/my-strategy/state/indicatorManifest.ts");
const cockpit = read("src/modules/strategy-lab/my-strategy/pages/StrategyCockpitPage.tsx");
const targetMatrix = read("src/modules/strategy-lab/my-strategy/cockpit/TargetSlotMatrix.tsx");
const targetsStep = read("src/modules/strategy-lab/my-strategy/wizard/TargetsStep.tsx");
const reviewStep = read("src/modules/strategy-lab/my-strategy/wizard/ReviewStep.tsx");
const repository = read("server/strategy-automation/repository.js");
const service = read("server/strategy-automation/service.js");
const apiClient = read("src/modules/strategy-lab/automation/strategyAutomationApi.ts");
const migration = read("supabase/migrations/202608230001_my_strategy_draft_version_model.sql");
const archiveMigration = read("supabase/migrations/202608240001_strategy_automation_archive.sql");
const compose = read("infra/black-cloud/docker-compose.yml");

for (const label of ["Identity", "Indicator and Market", "Signal Mapping", "Execution Behavior", "Risk Management", "Filters and Schedule", "Take Profits and Exits", "Paper Account", "Execution Destination", "Activate Strategy & Save Configuration"]) assert.match(draftStore, new RegExp(`"${label}"`));
assert.equal((draftStore.match(/^\s*"(?:Identity|Indicator and Market|Signal Mapping|Execution Behavior|Risk Management|Filters and Schedule|Take Profits and Exits|Paper Account|Execution Destination|Activate Strategy & Save Configuration)",?$/gm) || []).length, 10);
assert.match(draftStore, /Strategy name must contain at least 2 characters/, "mandatory strategy name is validated at its own step");
assert.match(draftStore, /Select an existing Black Terminal indicator or one of your saved scripts/, "indicator selection is mandatory");
assert.match(draftStore, /Long Trigger Entry/);
assert.match(draftStore, /Short Trigger Entry/);
assert.match(draftStore, /Buy Trigger Entry/);
assert.match(draftStore, /Sell Trigger Entry/, "Spot uses Buy/Sell semantics instead of Long/Short");

for (const label of ["My Strategy", "Backtest", "Paper Trading", "Live Automation", "Analytics", "Research", "Logs"]) assert.match(tabs, new RegExp(`label: "${label}"`));
for (const researchTool of ["Optimization", "Heatmap", "AI Review", "Code Suggestions", "Forward Test"]) {
  assert.doesNotMatch(tabs, new RegExp(`label: "${researchTool}"`), `${researchTool} is not a primary Strategy Lab tab`);
  assert.match(page, new RegExp(`"${researchTool}"`), `${researchTool} remains available under Research`);
}

assert.match(library, /CREATE NEW STRATEGY/);
assert.match(library, /strategies\.map/);
assert.match(library, /MODIFY STRATEGY/);
assert.match(library, /DELETE STRATEGY/);
assert.match(library, /aria-haspopup="menu"/);
assert.doesNotMatch(library, /BC-QALC|START FROM TEMPLATE|qalc-template-card/, "the library contains only user-created strategies");
assert.match(experience, /Modifying the saved draft/);
assert.match(experience, /DeleteStrategyDialog/);
assert.match(experience, /No broker order is placed, changed or cancelled/);
assert.match(apiClient, /mutation\(\{ expectedName: strategy\.name, expectedRevision: strategy\.draftRevision \|\| 0 \}, "DELETE"\)/);
assert.match(service, /req\.method === "DELETE"[\s\S]*archiveStrategy/);
assert.doesNotMatch(library, /StrategyDefinitionBuilder|NAME STRATEGY BEFORE SAVING/);
assert.equal((wizard.match(/step === \d/g) || []).length, 10, "wizard renders only the active step");
assert.match(indicator, /Nothing selected/);
assert.match(indicator, /none is selected automatically/);
assert.match(draftStore, /indicator: undefined/);
assert.match(draftStore, /runtimeKind: "external-signals"/, "new strategies start without a preselected signal engine");
assert.doesNotMatch(indicator, /START FROM A TEMPLATE|strategy-template-picker/, "the wizard has no default strategy templates");
assert.match(indicator, /Current chart:.*Runtime:/s, "strategy timeframe is explicitly independent of chart timeframe");
assert.match(indicator, /\["SPOT", "FUTURES"\]/);
assert.match(manifest, /source: "ACTIVE_CHART"/);
assert.match(manifest, /source: "CUSTOM"/);
assert.match(manifest, /source: active \? "ACTIVE_CHART" : "BUILT_IN"/);
assert.match(manifest, /\["indicator", "strategy"\]/, "owned Script Editor indicators and strategies are selectable signal sources");
assert.match(manifest, /runtimeStatus: "REQUIRES_CERTIFICATION"/, "owned custom scripts fail closed until server certification exists");
assert.match(manifest, /configuredAlerts/);

for (const tab of ["OVERVIEW", "CONFIGURATION", "PAPER", "LIVE TARGETS", "POSITIONS", "TRADES", "PERFORMANCE", "RISK", "LOGS"]) assert.match(cockpit, new RegExp(tab));
assert.match(cockpit, /rows\.length > 100/, "large Paper tables use windowed rendering");
assert.match(targetMatrix, /Array\.from\(\{ length: 10 \}/);
assert.match(targetMatrix, /No execution destination assigned/);
assert.match(targetMatrix, /bindings\.filter/, "only occupied bindings create detailed state");
for (const destination of ["Paper Backtester", "Connected Broker", "Investment Group"]) assert.match(targetsStep, new RegExp(destination));
assert.match(targetsStep, /AUTHORIZE THIS DESTINATION/);
assert.match(targetsStep, /ARM AFTER ACTIVATION/);
assert.doesNotMatch(targetsStep, /apiKey|apiSecret|type="password"/, "Strategy Lab references pre-connected targets and never handles credentials");
assert.match(experience, /eligibleTargets/);
assert.match(experience, /plan\.armOnActivation/);
assert.match(experience, /strategyAutomationApi\.addTarget/);
assert.match(draftStore, /perpetualSignalReversalEnabled: false/);
assert.match(draftStore, /stopReversalEnabled: false/);
assert.match(reviewStep, /Activate Strategy &amp; Save Configuration/);
assert.doesNotMatch(reviewStep, /PUBLISH VERSION|Review and publish/i, "private strategy activation is not described as public publishing");
assert.doesNotMatch(`${experience}\n${library}\n${wizard}\n${cockpit}`, /localStorage\.setItem|sessionStorage\.setItem/, "server state is authoritative; the workflow does not duplicate strategy persistence in browser storage");
assert.equal((experience.match(/setInterval\(/g) || []).length, 1, "one cockpit snapshot poller is mounted");
assert.match(repository, /strategy_paper_accounts"\)\.select\("id,strategy_id,strategy_version,/, "strategy library retains the canonical Paper account identity");
assert.match(repository, /strategy_automation_trades"\)\.select\("strategy_id,paper_account_id"\)/, "trade summaries use columns that exist in the execution ledger");
assert.match(repository, /paper_account_id === paper\.id/, "trade counts are scoped to the selected published\/running Paper version");
assert.doesNotMatch(repository, /strategy_automation_trades"\)\.select\("strategy_id,strategy_version"\)/, "strategy trades do not query the nonexistent strategy_version column");

assert.match(migration, /black_core_save_strategy_draft/);
assert.match(migration, /black_core_publish_strategy_draft/);
assert.match(migration, /black_core_start_strategy_version/);
assert.match(migration, /running_version/);
assert.match(migration, /status='PAUSED'/);
assert.doesNotMatch(migration, /strategy_target_bindings.*insert/is, "draft/publish migration creates no empty target rows");
assert.match(archiveMigration, /black_core_archive_strategy/);
assert.match(archiveMigration, /status in \('LIVE','DISCONNECTING'\)/, "active broker targets fail closed instead of being silently detached");
assert.match(archiveMigration, /status in \('QUEUED','PROCESSING','RETRY','SUBMISSION_UNKNOWN','RECONCILING'\)/, "pending broker commands must settle before deletion");
assert.match(archiveMigration, /brokerOrderMutation',false/, "delete audit explicitly records that no broker order mutation occurred");
assert.doesNotMatch(archiveMigration, /delete from public\./i, "user-facing delete retains immutable strategy history");
assert.match(compose, /STRATEGY_AUTOMATION_DEMO_EXECUTION_ENABLED: "true"/);
assert.match(compose, /STRATEGY_AUTOMATION_LIVE_EXECUTION_ENABLED: "true"/);
assert.match(compose, /STRATEGY_AUTOMATION_LIVE_EXECUTION_CERTIFIED: "true"/);
assert.match(compose, /STRATEGY_AUTOMATION_GROUP_EXECUTION_ENABLED: "true"/);

console.log("My Strategy UX tests PASS — empty strategy library, explicit indicator selection, private activation, ten-step workflow, versioning, cockpit navigation and destination controls verified.");
